# 设置当前路径
DIR_ROOT:=../..

DIR_LIST_SUB :=\
cpp

FILE_LIST_C +=\


FILE_LIST_CPP +=\



FILE_LIST_S +=\



DIR_LIST_INCLUDE+=\
$(DIR_ROOT)/include/opencv4\

DIR_LIST_DDL+=\
opencv_gapi \
opencv_highgui \
opencv_ml \
opencv_objdetect \
opencv_photo \
opencv_stitching \
opencv_video \
opencv_calib3d \
opencv_features2d \
opencv_dnn \
opencv_flann \
opencv_videoio \
opencv_imgcodecs \
opencv_imgproc \
opencv_core \


include $(DIR_ROOT)/make_conf.mk
all:make_show make_app
clean:make_clean
include $(DIR_ROOT)/make_fun.mk
