# 设置当前路径
DIR_ROOT:=../..

DIR_LIST_SUB :=\

FILE_LIST_C +=\


FILE_LIST_CPP +=\
writeImage.cpp\


FILE_LIST_CPP +=\


FILE_LIST_S +=\



DIR_LIST_INCLUDE+=\
$(DIR_ROOT)/include/exif\

DIR_LIST_DDL+=\
exif\



include $(DIR_ROOT)/make_conf.mk
all:make_show make_app
clean:make_clean
include $(DIR_ROOT)/make_fun.mk