DIR_ROOT:=..

DIR_LIST_SUB :=\
json\



FILE_LIST_C +=\


FILE_LIST_CPP +=\


FILE_LIST_S +=\



DIR_LIST_INCLUDE+=\




include $(DIR_ROOT)/make_conf.mk 
all:make_show make_subdir
clean:make_clean
include $(DIR_ROOT)/make_fun.mk